services:
  - type: web
    name: ai-invoice-parser
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=5000
    envVars:
      - key: PORT
        value: 5000
